// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MysticRiver.Application.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MysticRiver.Application.Migrations;
[DbContext(typeof(MysticRiverDbContext))]
[Migration("20260609192744_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("MysticRiver.Application.Data.Entities.BattleSessionEntity", b =>
            {
                b.Property<string>("BattleId")
                    .HasColumnType("text");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("CurrentTurnCreatureId")
                    .HasColumnType("text");

                b.Property<int>("EnemyAttackPower")
                    .HasColumnType("integer");

                b.Property<int>("ForcedEndReason")
                    .HasColumnType("integer");

                b.Property<string>("ForcedWinnerCreatureId")
                    .HasColumnType("text");

                b.Property<string>("GuestPlayerId")
                    .HasColumnType("text");

                b.Property<string>("HostPlayerId")
                    .HasColumnType("text");

                b.Property<int>("MatchStatus")
                    .HasColumnType("integer");

                b.Property<int>("RoundNumber")
                    .HasColumnType("integer");

                b.Property<int>("StateVersion")
                    .HasColumnType("integer");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("BattleId");

                b.ToTable("BattleSessions");
            });

        modelBuilder.Entity("MysticRiver.Application.Data.Entities.CreatureSnapshotEntity", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("BattleId")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("CreatureId")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("Hp")
                    .HasColumnType("integer");

                b.Property<int>("Mana")
                    .HasColumnType("integer");

                b.Property<int>("MaxHp")
                    .HasColumnType("integer");

                b.Property<int>("MaxMana")
                    .HasColumnType("integer");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("Shield")
                    .HasColumnType("integer");

                b.Property<string>("StatusEffectsJson")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("BattleId", "CreatureId")
                    .IsUnique();

                b.ToTable("CreatureSnapshots");
            });

        modelBuilder.Entity("MysticRiver.Application.Data.Entities.CreatureSnapshotEntity", b =>
            {
                b.HasOne("MysticRiver.Application.Data.Entities.BattleSessionEntity", "BattleSession")
                    .WithMany("CreatureSnapshots")
                    .HasForeignKey("BattleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("BattleSession");
            });

        modelBuilder.Entity("MysticRiver.Application.Data.Entities.BattleSessionEntity", b =>
            {
                b.Navigation("CreatureSnapshots");
            });
#pragma warning restore 612, 618
    }
}
