apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mysticriver-api
spec:
  rules:
  - host: mysticriver.pm4.init-lab.ch
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mysticriver-api
            port:
              number: 80