<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MysticRiver.Contracts\MysticRiver.Contracts.csproj" />
    <ProjectReference Include="..\MysticRiver.Domain\MysticRiver.Domain.csproj" />
  </ItemGroup>

</Project>
